### ISSUE TITLE
Features on Manifests not Generating Thumbnails When Not Present

### ISSUE THREAD

**Issue by markpbaggett** [CenterForDigitalHumanities/navplace-viewer#14]
In the README, it is suggested that a thumbnail will be added to a Feature on a Manifest if one does not exist by accessing the thumbnail on the first Canvas:

> For Manifests, if the Feature(s) do not have a thumbnail property, their thumbnail will be the image from the first Canvas if one exists. For Canvases, if the Feature(s) do not have a thumbnail property, their thumbnail will be the image from the Canvas if one exists. This does not apply to Ranges or Collections, as their structures are too complex for this kind of automatic support.

In my objects (here is an [example](https://centerfordigitalhumanities.github.io/navplace-viewer/?iiif-content=https://digital.lib.utk.edu/assemble/manifest/rfta/165)), that doesn't seem to be the case:

![image](https://user-images.githubusercontent.com/2692416/190711687-df400721-c319-41ad-a99d-4fec0f735fcd.png)

Here is the thumbnail on the first Canvas for this object. The `id` points at a thumbnail, but the Image API in `service` can also be used:

![image](https://user-images.githubusercontent.com/2692416/190713747-a81ea4b2-591b-4cda-8965-17055ef0276c.png)

Do I have something wrong here, or does this no longer work?

**Comment by cubap** [comment]
I see an error fetching `https://iiif.lib.utk.edu/assemble/manifest/rfta/165/canvas/0` which may be related to why there isn't something showing up here.

**Comment by markpbaggett** [comment]
@cubap, apologies.  I see now that I did something bad with our non-dereferenceable `id` properties.  I assumed the pattern I used would result in a 404, but they don't.  Sorry for wasting your time with this. I'll close this and fix my presentation endpoint to see if that fixes things.
