### ISSUE TITLE
Starting Zoom

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/navplace-viewer#20]
Sometimes it is very difficult to see where your non-point shapes are when you start zoomed out to see the continents.  Is there a way to detect geometries and load with them in view?

Aaron Straup Cope:

You can use the handy derive_bbox method here - https://github.com/whosonfirst/js-whosonfirst/blob/master/src/whosonfirst.geojson.js#L7

**Comment by yashaswini-slu** [comment]
you can use this for testing - https://map.rerum.io/?iiif-content=https://collection.sfomuseum.org/objects/1762832329/manifest/
